[build]
  command = "rm -rf node_modules package-lock.json && npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  # Prevent Netlify from failing on RevenueCat publishable keys
  SECRETS_SCAN_OMIT_KEYS = "VITE_REVENUECAT_ANDROID_KEY,VITE_REVENUECAT_IOS_KEY"
  # SECURITY: Do not set VITE_REVENUECAT_* variables here - they get bundled into client code
  # RevenueCat keys should be handled server-side or via secure runtime configuration
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_APP_ENV = "production"

# Note: API calls go directly to Hetzner server
# Single frontend architecture - no functions needed

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=self, microphone=(), geolocation=()"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
