// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pszxedsfbllqnkxyfdzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzenhlZHNmYmxscW5reHlmZHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTAwOTcsImV4cCI6MjA2NTU4NjA5N30.uQlsK2s-DaQkh7wpCr-FZckAuEtNthQmck9ruKkK5No";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);